# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checking out
        uses: actions/checkout@v2
        
      # Install NodeJs
      - name: Installing NodeJs
        uses: actions/setup-node@v2
        with:
            node-version: 12

      # Install Yarn
      - name: Installing Yarn
        uses: borales/actions-yarn@v2.0.0
        with:
            cmd: install
      
      #Build
      - name: chimpwizards-npm-build
  # You may pin to the exact commit or the version.
  # uses: chimpwizards-pipeline/npm-build@fad8b0d15e902bd8ed2cb931b3be4bf34b70d3fd
        uses: chimpwizards-pipeline/npm-build@v1.0.7
        
      # Install Surge
      - name: Installing Surge
        run: npm install --global surge
        
      - name: cURL AxiosJS
  # You may pin to the exact commit or the version.
  # uses: indiesdev/curl@60fb289d6e72261f095d7cefd578e659dd1b5182
        uses: indiesdev/curl@v1
        with:
          # The target url
          url: # optional
          # The request method, basically one of GET, POST, PUT, PATCH
          method: # optional, default is GET
          # List of status codes to be accepted, else it is considerred to be failed
          accept: # optional, default is 200201204
          # Headers object
          headers: # optional
          # Params object
          params: # optional
          # Body object
          body: # optional
          # timeout (millisec)
          timeout: # optional, default is 1000
          # Basic authentication, format =>  username:password
          basic-auth: # optional
          # Bearer Token
          bearer-token: # optional
          # Proxy host, format =>  host:port
          proxy-url: # optional
          # Proxy authentication, format =>  username:password
          proxy-auth: # optional
          # show debug message of response
          is_debug: # optional
          # custom config
          custom-config: # optional

          
      - name: Publish to surge.sh
      # You may pin to the exact commit or the version.

        uses: dswistowski/surge-sh-action@v1.0.1
        with:
    # your surge.sh domain to deploy
          domain: waseem602-counter-react-app.surge.sh
          login: wasimarif602@gmail.com 
    # surge.sh token, generate it with `surge token` command
          token: ${{ secrets.SURGE_TOKEN }}
    # your project path
          project: ./build
